# 5 GC - Computing GC Content
import re

sample_string = """
>Rosalind_6404
CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCC
TCCCACTAATAATTCTGAGG
>Rosalind_5959
CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCT
ATATCCATTTGTCAGCAGACACGC
>Rosalind_0808
CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGAC
TGGGAACCTGCGGGCAGTAGGTGGAAT"""


# sample_string = """
# >Rosalind_0432
# CGGAACGAGTGTTATGCGATAATGCAGGCCTTCCGCTAAACAGTCACGAGGACAATGCCC
# CGCAAATTCTATGAGCGAAACCATCGAAAGAGGATGGCTATCCTCCCAGCCCGCGGAGGC
# CTGGCTCGTGTCTCTGATTCCCAGGGTACGTTTTTGAGTCCGCGAAAGCTCATCTGCCCG
# CGATGACTACCCCGCAAGCACTACTGCCACGGGACCTCACGGACTTCTCCCATTACACTG
# AATAACGTAACTGTTTCCCAAAGTCACCCAGAGATTCCCTAATTCGGTTAAATTTAGTCG
# AGGTACACTGACTGGGGCTCGTGTGCCAGGATACCGGCGAGTCTGACAGCACACCCGTGT
# GAGCTTGTCCGACTTCCTCGAAGGAGTCCATGGTTATAGGCTCCTTAGAGGTTGGACCCG
# GCTAGACGCTGAGGGAGGTTGGGCGCCACGATACACCTCCCACTCTCTCGTAACACGCGC
# CTGGACGCTCTACACCCCGCCCGTTTGCTCAACGGCACGAATACGGCGGCCTCTATGTGG
# TGGGACCTGAACGGCCCTTGAAGGAGGTCGTCAAATTAAGGCCAATCTGAGTAATGCCAG
# CTGGAACTGGAGCGCCTGTTTATAAATGTCGTGAGAGTGCTCCGGGAATCTACAATCTCC
# CTGGTTCCTGTAATATTTCGAGCAGCTCCTGGGAACCTAAGATCGAATATGCAAGGCGCG
# GCTGAAAAGAGGGCGGAACCTTCAAATGATGTACGAGAATAGAGGTGGAGGTTTTGTGAC
# TAGACAGCATGCATATACCCGTTACCTTCCGCCTGACCCATAGTGAGGGAAATTATGTAA
# ACATCGCGAAGACCGCTCTGGCCCCACTTCCGGATTAGGCCGCATATCAGGTTTGCATAA
# CTTGGCCA
# >Rosalind_0785
# GCGGCGAGTATAATTTCCGATCGCTTTGACGAGGTTTTCCATTGAAAACAAAACCCGCGC
# GTAGAGCTAGTATTACGACTTATCTAACGACGATGACGTATTTTCCAGATATTAGAGACG
# GAAGAGTAAAAAGCATCAGTCTTACGATAGTCTGACCGGCCGTCTTTCAAATGGACCGAC
# CTCGACGGTAGGTGGAACGCTATCTAAAGTCAATTCACAGCCACCCACTAGGCAGAGATG
# GCCCTCTTTTAAGACGTTTCTCGGTTGCCCTGTCCGACCGCGGCGTCAAAGAGTTAAGAA
# CTTGTTAGAGGCATAGAGCACGGCTAGAGGTGTTGCCTTCATAGACGGGCGGACTAACTA
# TCCTTTATTAGCTGTTGGGATCCTAGGAGAGCAACGTCATTGAAGGGATTGCTGCAAGAT
# GGTCCTAGCATTCTAGCAACTTTATGCTGGGCGTTGCTTTCAATCGCACGACGCCAACAC
# CTTCAAAGGACCTGTAGGGACAGTGATTTACACTCCAAGGACTGATCCAGCGTGTCTAAA
# GCGCAGCTTAGCAATCCGACAATCCCACTAGGTTGTGAGCTCTAAATATGATAAACATCG
# GGAAGGTCCTCGAACCGTTACCCCGATCTAGTCCGGACCGAGAAAAGGCGGTGCTTGGTG
# CCAACACTCGACGGCACAGGCTCCAGAGTTTACGCACATAAAATCTAATGGGGAAATTGC
# GAAGGCCCGAATTCTTCCTTCGGCGGATCACTGCCCTTGGGACAAGAGATTGCACCTGCC
# GGAGTCGCGTAGGTATGCCGTAAAGC
# >Rosalind_6396
# TGCTATACAGGGATGGAATACTCCTGTCTCGCCATCCTTAGGGGGCAGGATTCTCGGAGT
# GACCCTTAGGGAAAGTTCGGCGGAGTGGTAAGTTCCGCCCTGTCAGAATGATCGCACGAC
# CCGCGTTGGATGTCTAACATCAGAAGATCCCCTTCACGTACCAACCCAATAGAGCTATGC
# AAGGACAATAGAAGCTGTGATTCTCGTCGGAGTGAGACTCAATACAGCTCTTTAGCACCT
# CACCACCCCAGGCCAAGGTCTACTGGAGTTCCACGGAGAATAATGACTACGTAGTGTCAC
# CGGGAGGTCCCTGGGCTGAGTGGTTACGTTGCGCGAGCGCGCCACTCAAATCTTTGTGGT
# TTCTCATGCATTAGCGCTATTTGTACCACCGGGCCAAGATAAGCAGAGGGTATCCACACC
# ACTGTCTGCGTCAATTTACCGAATGCAGATGAATGTCAATACTTGCAAATATAGGCGGGT
# CACTGGGACGGGCCGAGAATCGACCTGAGATTAGACCGATCCAACAGGATCTCTGAATCT
# GTGTGACTTAGAGCGGGGTTCGGCCCCCCGGAGGAACAACCAACGTGATTAACTGAGCAT
# AGATAGCAGATGTACAGTATCAGTCTTTGTTGGCGCGCGGCACAGCTTCTGTCTCCAAAT
# AACCAGAATGAAATAACACCGGCTAACTGGGTCGTGACTACCGTACCTGAAGAGCAATAC
# CTGTAGTTATCTATACTAGGTAGGTATATACCCGGATGCATGAGTTGCCCCACCAATGCG
# ATGTCTCGCTTTAACACGCAACAAGATCCTACAAGGGG
# >Rosalind_5324
# GATTGGGGCATATGCTAGGTACTCACTTGCCTAGTGTGCCTATGCCTGAGCCCACGTTAA
# CTGAAGTGTGCGTACCGGGGAGACCTGACTCGTACCCTCAAGCAGGGAAGTCGGTGGACG
# CCTGGCAAACGCCTACCGCTAGTGTAGTGTTGTAACGATTACGCCGCCTGCACGAGGCTA
# GATCTAAGTAGCGCTCAAAGGAACTGGCTTTCAGTACCGTTGGTCAGTAACCTCGCGTCC
# AATCACGACTCTCAACCAACTTATAACATAAGGGACCGCGCTAACTGCGTAGTCCATAAG
# CAGCGTCGCTGCGAAGAGCAAAGTGGCGAGAATTACAGCTTAGTATAGTACAAGTCCTCG
# ATCTGTACATAGCCCCTTCCATTTGTCACTACAAGCAATTGGCCATATCTGATTACATAA
# TCACGCCAGCGGGCTGAGCTTCCGTAGAAACAGTTATGCAGCGGCCTTACTGAACCTGCG
# CTCGCAACAATTAAACTTAGTCGTGAAGACAAGGCTGATTGCGACTAAGCTTCTGCTCTA
# GGGTAGTAGCACAGCCGAACAGTCGCGCAGGCATTTAAAGCCTAAATTGGCGGGAACAAG
# AGCCGTCACCCCTCAATTGCAAGTTGCTGCCTTCCCTGCAGACATCAAATAGGCAGACGC
# GTCCTCTTCGAGCTGGATCACGGTACAGAAGTGTGAGCGCGCTGTGCAATGCTCTCATGC
# GCGTCGAGGAAACCAGACCTACGATGACAAAAAAATTTCCTTAAAGAATCGAGATTACTG
# GTGTCACCAAAAACTGTTAGGGATAAACGTAAGTTGACCTGGCGCCTCAT
# >Rosalind_6037
# GACGTGGATTACGAAGACGCGACGGAGCCGAAAGCCACGCCGATGTGGGGTTAGTTCCAG
# CATAAGTGGCGATATGCCATAATGATGTTTAAACAAGTATAACGTAATCGGAGCTAAATG
# CGACTCGTATAGTCTTTAACGTGCGCGTATTCATCCCTCGCTATAGGATAGCATTTGATG
# AGTCCTGGCCTCCTTGATTAAAATTGCCCTCGAAAGGTAACGTCAAACTCAGGGCGCGCT
# AGTAATGCAAAGCTAGCGCCCCCTCCGCGGAGTCGCCGGGGACTTCCCTATTTCGTTCCA
# CACGGTCTGGAACTTGATTTCAGCGACGGAGGAAGGAGGCATTAGCAGGTTTCCGAGAAG
# GGACATTGTTTCTCCTCGCATCGAATGTACTTATCCAAATTCTGGATTATTACCCGTATG
# AACGCTAAGACACGATTTTAAGGGTGACGGACATATGTCGATTTTGATTTTAGGTTCGGA
# AACCCCGACTTTGAGTTTTCCGTAGTGTGCTAGCCCGCTACGAAATATAGGAATTCGACA
# GTTCGGGCCGTCGGACAACGTCCGCGTGAGATAGGTGATGAGCAAGTTAAGTCCCATCTG
# ATAGCGCGTGTCTTCAGCCAGTTGTCTTAGAAACGTCCCTAACATATACCCCCATCGCGG
# CCCGGGATGAACCGGAAGCCTGAGCGGGACTACTCAGTTGATTGACACATGTCCCGCTGC
# ACCCGACCAGCTCCTGAGTAAGCACACAATATACGTTCGATGCGTCGTCGGAATGCTTTC
# CAAGGCATTGAACTTCTAGCCCAGCTCTATGCCTACGAGGTTCAGGGGTCACCCATAGCA
# TCATATTGGGCCAGACAATCAAAC
# >Rosalind_4110
# CGACGTAATGATGTTCCAATAGGTTAGGCATATCAAAGACACGCTGCCGCTAGGTGGCCA
# ACGCTCGGGACCTAAGGTTGCAAAGGTCAGCAAAATGAACCATTTCATAAGACTAACGGT
# ACGAAACATTCACGAGATAGGATTCGCGATCTCAACCTACGCAAAGGATAATCCATTAGC
# GCCTTACGGAGCGGCGCCTACGCGCCTGCGTGGATACGTGCGGGATGTGGAGTCCTTCCC
# TACCTTGCAATGGTTCGGGGAAGGTTTTGGCGATGAGAGGCGCATATGCCTCATCAGCAC
# AATTCACATAGTCGAATCACCATGACGTACTGCACCCTCCTGTTTGTTCTTGTGACGATG
# CAGGACTCCGCACAGACACCTATCAAAGCACCCATCTAGAGAACGTGGACCGCGGTTCTC
# GCTGACTTTTTCGTACGGAAGTTTGACGATACTGCAGCTTTACCAACATTGACCCTGACT
# TTGATACAAGAAAACTAGTTCGAGAGCCCACCTACCCCTGCGGCATACCCGATGAGACTA
# GTTATAGTCCTATAAGTGGGCGCATGCAGTTGTAGGGATAACATCCTTGGGCGGAGACTC
# TGGTCGTAGGTTGCATCCCCAAGCAACATAGGGTCGCATTCAATACACGAGATGCCGCAA
# GCCTGGGTGATTTATAGCCGCACAATCATAGCAGAAACCGTATCGGCGAGGCTAGCGTTC
# TCCAGATCAGGACCTAGCACCGTCTCTGACAAGATGCATAATCTCTACATTAACATAGTA
# ACGCAATTGGTTCAGCTAATGTCAACTGAAACCGCTGACACAGATACTGAGTCCCCACCA
# CGACGCATC
# >Rosalind_4488
# TCAATTCCGATCACCCCTTCTCGGCCCTTCAGGGCTCGACGTCCGCTGTACAAGGTGAGT
# TGGGGACCCGGACGCCTTAGACCTAATGACTCCAAGAGTCAGTACTCACAACGCCGCCGA
# GAGGCGTACGGCACGTTACCGAGCACGGGAGTTTGTTAGAGGTGCCGTGAGATGGTCGGG
# AGAGCTGGCCGCTTCGCAGATTGTACGTTATACGAGCTTAAGTGTAAACGAACTAGCCCA
# ACAAAACTCCATATGCGGACCTAACCCGCTTTTAGCCCGTTAAGACTACCAAGTCTGAAA
# TAGCGCGGTAATTGTATGAGCATACGACTCCTCGGCTGCACACGCTGGACAAACAGCGAC
# GAGTATTTAATTTGGATTGAAACACGCCTACGTGTATTTTGACCATCGGGCTGCAGTAAA
# CATCTCCATGGTGCAATAGGTGTAGTCTCCCGCGAGCCCGCACGCCATGACGCTAACGAG
# CAAGATGTGTAGTTTCCATTAGCCTCGTAGTCAAGTTGGGTATCTCTTCACCGTGCGTTG
# CCGAGCAGCAGTAGTATCAGACCGGGACTTTCCCGTAACCCTACGGGGCTTGTTCGTGTT
# GGTGTTCGAATGTAGTCAAACATTTTGCTCCGCATCGTTGATTCATGTAAGACCAGTAAG
# TTCTTTTGCATGGCACATTATGAGTCTATCACTTTGCCGCCCAACTAAAGAGGCCGTAAC
# GGGCTGATCACAGCCGAGATACAGGCACCCTGGTGAGCAGGGAGTTAGCGGAGTTCTCGT
# TCCATGTCCCTGTACCCCTTCTGCAACAACTACGTTCCTTAGGTGGCTGGAGGGTTCATC
# ATTGCAGTTTCCTACCAAGTGCTATCGTATCTATTACTACGCATGAGAGAACGGCACAGA
# CGTCCACTGGGCACAGTGATTCGTAGGGCCAATGGTGGTGATGGTTGTACATTAA
# """

def compute_gc_content(string):
    try:
        id_list = list()
        temp_list, encode_list = list(), list()

        for i in re.split(r'\s', string):
            if re.match(r'>', i): id_list.append(i)
        for i in re.split(r'\>[\w]{8}_+[0-9]{4}', string):
            encode_list.append(i)

        for i in range(0, len(encode_list)):
            c_count = encode_list[i].replace("\n", "").count("C")
            g_count = encode_list[i].replace("\n", "").count("G")
            count = len(encode_list[i].replace("\n", ""))
            if not count == 0:
                gc_content = (c_count + g_count) / count
                temp_list.append(gc_content)
            else:
                continue
        index = temp_list.index(max(temp_list))
        id = id_list[index].split('>')[-1]
        return id, max(temp_list) * 100

    except Exception as error:
        return error


print(compute_gc_content(sample_string))