#1 Counting DNA Nucleotides: https://rosalind.info/problems/dna/

# sample_string = 'AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC'
sample_string = "CACTGATAACGGCAGTCTCGGTAACTAGGTCCGCAATTTCGAAGTTGATCGCTCATGACGACGAATGTTTTGAGCGGGGTAGTCAGTCCGGTAAATGTATGGGGACGGTCGTAACTGCCTCATATTAGAGTTAGTGCATACAGCTAAGCAATTTACTTCGTTCCGGCACCTAGCTGCCCAACCAGTTAGATTTAGGGTCTACGGACTTGGGATCGCGGTGCGTATTTTGGGGATGCACCACTGAAGTATTTCCCCCTAGTACTTAGGTGTCAGCTATGACTTTACGTTTGTGCTTAGGGGTTGAACGCTCTGGGACCACAGACGCTACGTAAGATCCCGGGGGACAATAACAGGGCGTGTGTTAAATCTGCGGTAAGCCTTTGGTGTCAGCGGTAACCAGTCGACGGGATCGTGGCTCGAATTTGCAGGACGAGCTGACTGATAGTTGTAACAAACTCGCCTAACGTCGTTTGAGCCGAATCCACCATATTTGAACCGCGGACGCAGCGGAAGAGGCGACGTCTTTCTTAACCCGTGGGCGCGACCCGTGCCAGAGCCGTGTTGATCATTCCCATCTTTTCGCCACACCTTCTCTAGCCTACCTCACTTTGGGACTTAGCTACGGTTTAGTATAGCGGAATCACGATACAAGCGTGGTTCATTTAGCCATGCCAAACTCGAAATACTACCATCTAGCAATCGCCGTCTCCGCCAAAGAGTCAGTATTACGCCTTGGCTTGATGAAATGACCTGCCTGCGGAAGCCGGTTCAGCCTATAATTTCGACCCGGCAAAAGACGTACGTACATGTCACGGTGCAATGATCCACGGCTTCTGTACAGCGTTGGTTTCGGGATTGTCGGACGGGTGCCATCCAGCTATAAGCTCGTTAGTACAAGCGGGAATGCCGAAATAGAGGCCGCTAGTCAAGT"

def counting_dna_nucleotides(string: str):
  try:
    a_count = string.lower().count('a')
    c_count = string.lower().count('c')
    g_count = string.lower().count('g')
    t_count = string.lower().count('t')
    return "{} {} {} {}".format(a_count, c_count, g_count, t_count)

  except Exception as error: return error

# a, c, g, t = counting_dna_nucleotides(sample_string)
# print(a, c, g, t)
counting_dna_nucleotides(sample_string)