# 3 REVC Complementing a Strand of DNA: https://rosalind.info/problems/revc/

sample_string = 'AAAACCCGGT'


# sample_string = "ATCCTTCGGCATTTGAAATAAGAAGGAGCCGAGTACAGGCTTGGACCCAAAGAGAGCTTTAAACTCACTGCTGTGTACGGCTAAGCTCCGGTGGGATTTCGCACAGCCAGTCGGGAGGAACGCTGACCAATGAATAGTTCCCTGTGACTAACCTAGCAAAGAGCATATGATGGAGTGGAAAACTAACCATTGCGCACGAATACCACCATCAGATCCGACGACTAGTCGATGCGTAATTAAGCAATGCATCGGACAGTCACCGGGGGGGGAGGGCCTGGCTATATTCTTACATTAGATTCGTGGTCGTTAGTGCGACTGTGAGAAGTACTCTTATTGACCATTTCAACCCCATCCGTACTCCCAACTGTTGCAGGATCTAGCGTCATCCACGAGCACGAACAAGTAGGCAGCCGAATACTGGTGAAATCTTCATCAGTGCAGCAATATCAAACCATGCCCCGACCGCTTTACCACCTCGCTAATGCTACACCATCAATTTTTTTTACTTATGAAGGAGAATGGTGGAGGGGAAGTTGACGAGGAAGAGTTCACTAAAGGGCGTGACAGGGTAGGGTAACTCAGTCAAACTTTTCTGACCCAGAGGGATGCTACCCCAAAGAGAGGAGAAACGTAAGAACTAACGTCACAGCTCGATGACGTACTACACTGGTTAGCCAACAAGTACGACATGGATTGCGACTGTCCTGACTGTACGTCATGTGTAGTACTCGTGTTCCCGCCATCGAGTGCGCGTATTTTGCACCCACTGGACCCCTTAACGCACCATTAGCACATGATATCATTGTCGCCTCCAAATCATGTGTTATAGCTACATTCACTGGTTCGAGAACGAAGCCCGAGGGATATATCCTATTCGGCGGTGAAACGTGATCAGGTTC"

def comp_strand_of_dna(string: str):
    try:
        _str = ''
        for i in string[::-1]:
            if i.lower() == 'a':
                _str += "T"
            elif i.lower() == 'c':
                _str += "G"
            elif i.lower() == 'g':
                _str += "C"
            elif i.lower() == 't':
                _str += "A"
            else:
                pass
        return _str

    except Exception as error:
        return error


print(comp_strand_of_dna(sample_string))
print("Checking with the result from website:", comp_strand_of_dna(sample_string) == "ACCGGGTTTT")
